### PR TITLE
Monst3r lines and Informant DB-scrubbing rework

### PR DESCRIPTION
**Pull request by qoala**
* Add/update text of Monst3r's mission lines
* Associate Monst3r's lines with the corresponding voice files
* Fix a minor bug with the luxury nanofab's column headers (broken by shopType change)
* Rework the camera DB behavior on Informant missions to match the voice lines
  * Camera DB can be scrubbed for cameras _and_ drones
  * Each turn of hacking scrubs only _one_ device
  * After each scrub, reboots one random device.

### CODE REVIEW

**Comment by Hekateras** [comment]
Note to other maintainers: Definitely do not merge yet

**Review by Hekateras — CHANGES_REQUESTED** [review]
@qoala
[Combine cameras and drones in witness-tracker display](https://github.com/Mobbstar/InvisibleInc-MoreMissions/pull/202/commits/4243003442f8ed8c10c0affdbc95c9b2d0e17f05)

No, we still want the player to be able to see how many witnesses of each type they have, since centralised scrubbing is one way to get rid of them but not the only one.
Consider: If a camera drone saw you and it only says '1 device', you have to mouse over every camera and drone until you find the correct one just s you can murder it with Tony's arm

Lumping them in together as 'devices' in VA was for the purpose of not re-recording otherwise nearly-identical variants, not because this is meant to reflect the new gameplay.

Please remove this commit entirely from the PR

**Comment by qoala** [comment]
Added changes since previous review:

* Reverted the change that merged cameras and drones on the Witness Tracker.
* Instead changed the subtext for drones to use the same as cameras, to mention the cameraDB
* Also realized that the tooltip needed this as well
  image

Scrub behavior is still the initial attempt that I tried. Alternate "witness list" displays that I showed on Discord (https://discord.com/channels/313015356052471828/589089660064628736/1193648231809290322) as a trial are not yet in this PR.

**Comment by qoala** [comment]
Add witness list to tracker-daemon's tooltip:

image

(Could've maybe omitted SECURITY CAMERA, but with Worldgen Extended, maybe we're differentiating Sec and IR cameras)

**Pull request merged**
